AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Chain of responsibility test with Lambda
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ChainORrespFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Description: Chain of responsibility test with Lambda
    Properties:
      CodeUri: app/
      Handler: build/app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        ChainORresp:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Description: >
            Chain-of-responsibility pattern.
          Properties:
            Path: /{proxy+}
            Method: get
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ChainORrespApi:
    Description: "API Gateway endpoint."
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/test"
  ChainORrespFunction:
    Description: "Chain-of-responsibility pattern Lambda Function ARN"
    Value: !GetAtt ChainORrespFunction.Arn
  ChainORrespFunctionIamRole:
    Description: "Implicit IAM Role created for the Analtyics function"
    Value: !GetAtt ChainORrespFunctionRole.Arn
